engines:
  duplications:
    enabled: false
    config:
      languages:
        #mass_threshold: 30
        - javascript
  eslint:
    enabled: true
    checks:
      comma-dangle:
        enabled: false
  fixme:
    enabled: true
languages:
  JavaScript: true
exclude_paths:
- "coverage"
- "helpers/"
- "tests"
- .gitignore
- .eslintignore
- .travis.yml