engines:
  rubocop:
    enabled: false
  eslint:
    enabled: true
    checks:
      comma-dangle:
        enabled: false
  duplications:
    enabled: false
    config:
      languages:
        #mass_threshold: 30
        - javascript
exclude_paths:
- "coverage"
- "helpers/"
- "tests"
- .gitignore
- .eslintignore
- .travis.yml
