dist: trusty
language: node_js
node_js:
  - "7"
services:
  - postgresql

postgres:
 adapter: postgresql
 database: myapp_test
 username: postgres

before_script:
  - psql -c 'create database docman_test;' -U postgres
  - dropdb --if-exists travis && createdb travis
  - sequelize db:migrate:undo:all
  - npm install
  - sequelize db:migrate

script:
  - npm run coverage

after_success:
  - npm test
  - npm run coverage
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < lcov.info
  - npm run codeclimate

addons:
  code_climate:
    repo_token: 15f145fdea863c28c680b0d22d8c07afa12b3c969ac94344ef63766e961df243

after_failure:
  - npm run coverage
